global:
  scrape_interval: 3s

  external_labels:
    monitor: "example-app"

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name: "app1"
    static_configs:
      - targets: ['host.docker.internal:5001']

  - job_name: "app2"
    static_configs:
      - targets: ['host.docker.internal:5002']